# Working with numpy


In [1]:
import numpy as np

### Creating a numpy array

In [2]:
a = np.array([1,2,3,4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([[[2,3,4,5], [6,5,3,4], [9,8,6,4]]])
print(b.shape)

(1, 3, 4)


In [5]:
b.ndim

3

In [6]:
b.dtype

dtype('int32')

In [7]:
b.dtype.name

'int32'

### Using arays to perform Matrix calculation

In [8]:
matrix_1 = np.array([[1, 1], [0, 1]])
matrix_2 = np.array([[2, 0], [3, 4]])

In [9]:
matrix_2 % matrix_1

C:\Users\SHOLA BODUNRIN\New folder\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0],
       [0, 0]], dtype=int32)

In [10]:
matrix_2 * matrix_1

array([[2, 0],
       [0, 4]])

In [11]:
np.dot(matrix_1, matrix_2)

array([[5, 4],
       [3, 4]])

### Slicing and Indexing

In [12]:
b[0, 1, 2]

3

In [13]:
matrix_2[0, :]

array([2, 0])

In [14]:
matrix_2[:, 1]

array([0, 4])

### Shape manipulation

In [15]:
b.ravel()

array([2, 3, 4, 5, 6, 5, 3, 4, 9, 8, 6, 4])

In [16]:
b.reshape(2, 3, 2)

array([[[2, 3],
        [4, 5],
        [6, 5]],

       [[3, 4],
        [9, 8],
        [6, 4]]])

In [17]:
b.ndim

3

In [18]:
b.transpose()

array([[[2],
        [6],
        [9]],

       [[3],
        [5],
        [8]],

       [[4],
        [3],
        [6]],

       [[5],
        [4],
        [4]]])

# Pandas Series and DataFrame

In [19]:
import pandas as pd

In [20]:
pd.Series(np.random.randn(5))

0    0.828872
1    0.062652
2    0.111842
3    1.672369
4   -0.294052
dtype: float64

In [21]:
pd.Series(np.random.randn(5), index= ['e', 'd', 'c', 'b', 'a'])

e   -1.184313
d    0.529996
c   -0.250015
b   -1.433981
a   -1.298803
dtype: float64

In [31]:
D = pd.Series({"a": 10, "b": 23, "c": 45, "d": 43})

SyntaxError: invalid syntax (<ipython-input-31-42ee8f217a1e>, line 1)

### To handle 3D data, the panel method is used

In [23]:
# d= {"item1": pd.DataFrame(np.random.rand(4,3)), 
#     "item2": pd.DataFrame(np.random.randn(4, 2))}
# cee= pd.Panel(d)

IndentationError: unexpected indent (<ipython-input-23-baf7a7aa5d55>, line 2)

In [ ]:
# cee

In [ ]:
# print(cee)

In [32]:
df = pd.DataFrame(D)

In [24]:
df1 = pd.DataFrame({"A":["A0", "B0", "C0", "D0"], 
                    "B":["A1", "B1", "C1", "D1"], 
                    "C":["A2", "B2", "C2", "D2"], 
                    "D":["A3", "B3", "C3", "D3"]}, 
                  index= [0, 1, 2, 3])

In [25]:
df1

A   B   C   D
0  A0  A1  A2  A3
1  B0  B1  B2  B3
2  C0  C1  C2  C3
3  D0  D1  D2  D3

In [36]:
D

a    10
b    23
c    45
d    43
dtype: int64

In [39]:
pd.concat([df, df1], axis= 1, )